"""
DATA MODELS MODULE
==================

This file defines the Pydantic models used for API requests, responses, and 
internal chat storage. FastAPI uses these to validate incoming JSON and to 
serialize responses; the chat service uses them when saving/loading sessions.

MODELS:
  ChatRequest   - Body of POST /chat and POST /chat/realtime (message + optional session_id).
  ChatResponse  - Body returned by both chat endpoints (response text + session_id).
  ChatMessage   - One message in a conversation (role + content). Used inside ChatHistory.
  ChatHistory   - Full conversation: session_id + list of ChatMessage. Used when saving to disk.
"""

from pydantic import BaseModel, Field
from typing import List, Optional


# ==============================================================================================================
# MESSAGE AND REQUEST/RESPONSE MODELS
# ==============================================================================================================

class ChatMessage(BaseModel):
    """
    A single message in a conversation (user or assistant).

    Stored in order inside a session. No timestamp; order defines chronology.
    """
    role: str # Either "user" (human) or "assistant" (Jarvis).
    content: str # The message text.

class ChatRequest (BaseModel):
    """
    Request body for POST /chat and POST /chat/realtime.

    - message: Required. The user's question or message. Must be 1-32_000 characters 
      (validated by Pydantic; empty or too long returns 422).
    - session_id: Optional. If omitted, the server creates a new session and returns
      its ID. If provided, the server uses it (and loads from disk if that session exists).
    """
    # ... means required; min/max length prevent empty input and token overflow.
    message: str = Field(..., min_length=1, max_length=32_000)
    session_id: Optional[str] = None


class ChatResponse(BaseModel):
    """
    Response body for POST /chat and POST /chat/realtime.

    - response: The assistant's reply to the user's message.
    - session_id: The session ID for this conversation. If the user provided one in the request, it's the same; if not, it's a new ID generated by the server.
    """
    response: str
    session_id: str